name: Deploy

on:
  workflow_dispatch:

env:
  APP_NAME: hhcv

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Get dependencies
      run: go mod download

    - name: Build application
      run: |
        GOOS=linux GOARCH=amd64 go build -o ${{ env.APP_NAME }} .
        chmod +x ${{ env.APP_NAME }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}-build
        path: ${{ env.APP_NAME }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Download application artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.APP_NAME }}-build

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy via SSH
      env:
        SSH_USER: ${{ secrets.SSH_USERNAME }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        APP_PATH: /usr/local/bin/${{ env.APP_NAME }}
        APP_DIR: /opt/${{ github.repository }}
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} << 'EOF'
          sudo mkdir -p "${APP_DIR}"
          sudo chown hhcv-deploy:hhcv-deploy "${APP_DIR}"
          sudo chmod 755 "${APP_DIR}"

          sudo systemctl stop "${APP_NAME}".service || true

          sudo mv "$(pwd)/${APP_NAME}" "${APP_PATH}"
          sudo chmod +x "${APP_PATH}"

          sudo systemctl restart "${APP_NAME}".service
        EOF
